version: 2
updates:
  - package-ecosystem: "npm"
    open-pull-requests-limit: 20
    directory: "/"
    schedule:
      interval: "yearly"
    assignees:
      - detzahard
    reviewers:
      - detzahard
  - package-ecosystem: "npm"
    open-pull-requests-limit: 20
    directory: "/fetcher/"
    schedule:
      interval: "yearly"
    assignees:
      - detzahard
    reviewers:
      - detzahard
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "yearly"
    assignees:
      - detzahard
    reviewers:
      - detzahard
